### ISSUE TITLE
All steps show as individual tests, and will not run

### ISSUE THREAD

**Issue by csurfleet** [ttutisani/Xunit.Gherkin.Quick#1]
I've followed the instructions for use, and I am seeing all the individual steps showing up in the VS test runner, and none of them will run.

I've added a complete example here:
https://github.com/csurfleet/GherkinQuickIssue

Any help would be brilliant, I'm running out of .net core options for gherkin now!

**Comment by ttutisani** [comment]
I will look into your sample in the evening, but meanwhile, can you mention what message it outputs in the test explorer when you run the scenario?
BTW, you mentioned it shows the steps. Did you mean it shows the scenarios? Do you use a regular built in runner to run unit tests (i.e. test explorer)? you should.

**Comment by csurfleet** [comment]
Hi, thanks for the really fast reply!

You were correct about the double period, I've actually tried both (. & ..) - as I've got the feature file in a subfolder in the solution - both give me the same result.

In both cases I see the step, not the feature in the Visual Studio test runner. When I try to run/debug them they just skip over and stay in the 'Not run tests' list

I've updated my project slightly now - its about as simple as it could get - the default .net core web api and a test project checking its ValuesController sends back a 200, so hopefully I'm doing something stupid!

**Comment by ttutisani** [comment]
You keep mentioning test runner. I assume you are using Test Explorer in visual studio. Is that correct?
You should not be using any test runner which is not built in. e.g. often people use ReSharper test runner thinking it's the right one. It's not, and it may produce different results than the built in one.

**Comment by csurfleet** [comment]
Yes, I'm using the default visual studio runner.

Out of interest, I can run this with the command line too, so that I can run on the build server? Thats going to be a requirement for me (although I could probably contribute towards that if its not there yet)

**Comment by ttutisani** [comment]
Yes, you can run it through command line. I actually myself use it in the CI of another project (https://ci.appveyor.com/project/ttutisani/portfoliotracker/branch/master). You can see there in the build log below (AcceptanceTests) that they run just fine.

So, you are using the right test explorer. Then you need to tell me now what exactly you see there. We may be using different terminology for the same thing. In your case, "Alive Monitoring" is the feature name, "Web request confirming system is alive" is the scenario name, and steps are under it (3 steps). So, do you see steps, scenario, or feature?

**Comment by ttutisani** [comment]
Hey, I found time now to look into your sample, and found the problem:

You need to derive your test class from Feature. That's mentioned in the Getting Started guide. I guess you missed that piece, which is very important.

That explains why you saw scenario steps and not the scenario instead.

If this solves your problem, let me know and this issue can be closed.

**Comment by csurfleet** [comment]
Hey, thanks a million for that - I've got things working now. Its brilliant for letting me move existing feature files into .net core projects, so thank you :)

I've noticed a few improvements I'd like to see, but I'm quite happy to contribute to add these in - how are you wanting me to deal with these? Add as issues then send you a PR? Briefly:
- A way of getting from the test to a feature - even if double clicking the test took me to the steps file that would be good (although the feature file would be better)
- The steps which have been run included in the test report - this should be quite simple to implement, but then I could click into any test in the runner, and see the list of steps executed and the results of each. This is important for showing to product owners etc here.

I'm going to have a try at integrating the test results into a Pickles document later on, I'll let you know how I get on with that.

Again, thanks for saving my life with this, I was starting to think it would be core or gherkin haha!

**Comment by ttutisani** [comment]
You're welcome! I'm glad it worked out well.

Yes, those suggestions are all great. So one issue per each, and a PR would do.
If any questions/doubts/findings on them, we can discuss further under those new issues.

Thank you!

**Comment by ttutisani** [comment]
So, lessons learned for myself to update/emphasize somewhere in docs, and for other readers who land here:

- `FeatureFileAttribute` takes file path relative to output folder, not relative to the class file.
- BTW, `FeatureFileAttribute` is not necessary of the class name matches the filename under default conventions: file should have ".feature" extension, and should be placed in the root output folder. e.g. "MyNiceUseCase.cs" => MyNiceUseCase.feature
- Class that contains step definition methods, should derive from `Feature` class, which is provided by Xunit.Gherkin.Quick library.

**Comment by ttutisani** [comment]
I'm reopening this because there are action items which I need to do (documentation updates) to consider this fully done. I'll keep this open as a reminder for that until I'm done with that.

**Comment by ChristianPejrup** [comment]
Hi just read this issue and at least the title has some overlap with issue #11 - i think it might fix the steps are showing up as tests issue.

**Comment by ttutisani** [comment]
Well, here the issue was that @csurfleet was not inheriting his feature class from `Feature` base class. That's anyway necessary to do to run the Scenario, because that's where (in the base class) the scenario method is defined.

**Comment by ttutisani** [comment]
Closing as all action items are complete now.
