### ISSUE TITLE
Tests not found after xunit gherkin implementation

### ISSUE THREAD

**Issue by Chrys123** [ttutisani/Xunit.Gherkin.Quick#105]
I have followed the guide, done the mapping etc and now the tests are not found.

Before this implementation they where running as normal

**Comment by ttutisani** [comment]
Can you please provide more details? Also, please clarify what you mean by mapping and before/after implementation?

**Comment by ttutisani** [comment]
Closing this issue as stale since I have not heard back from the issue author. Please open a new issue if you encounter the mentioned problem and cannot find the answer in the documentation pages.
