### ISSUE TITLE
Feature files not discovered by test explorer in Visual Studio v. 17.6.2

### ISSUE THREAD

**Issue by Daniel8770** [ttutisani/Xunit.Gherkin.Quick#142]
Hi, 

I recently updated my Visual Studio from version 17.4.1 to 17.6.2 which resulted in the test explorer not finding my feature files.

I can run my feature files in the command line using 'dotnet test', so it seems like it's an issue with the test explorer only.

Nothing was changed, except the update of Visual Studio.

I use the following feature file attribute: `[FeatureFile(@".*\.feature", FeatureFilePathType.Regex)]`.

I have Xunit.Gherkin.Quick cloned and am currently not using the NuGet package.

**Comment by ttutisani** [comment]
Do the tests in ProjectConsumer project pass with the new version of visual studio? Since you have the clone of the repo, you should be able to open the main solution file (Xunit.Gherkin.Quick.sln) and verify that the ProjectConsumer tests are working fine.

**Comment by Daniel8770** [comment]
Thanks for the answer.
The problem seemed to fix itself after uninstalling the update and installing it again.
I am now able to see and run the tests.

**Comment by ttutisani** [comment]
Thank you! I will be closing the ticket.
