### ISSUE TITLE
Scenario Outlines parser consider less operator ("<") as a starting char of an Example and searches for a wrong instance in the table.

### ISSUE THREAD

**Issue by farost** [ttutisani/Xunit.Gherkin.Quick#149]
Boolean expressions containing less and less or equal operators make Scenario Outlines tests fail.

### Examples:

**.cs:**
```
[When(@"code block {} is sent")]
public void CodeBlockIsSent(string codeBlock)
{
    System.Console.WriteLine(codeBlock);
}

[Then(@"parsed variables are {} and {}")]
public void ParsedVariablesAreAnd(string a, string b)
{
    System.Console.WriteLine($"A: {a}, B: {b}");
}
```

### Positive case:

**.feature:**
```
Scenario Outline: Parse comparisons
  When code block "bool result = <a> > <b>;" is sent
  Then parsed variables are <a> and <b>
  Examples:
    | a  | b  |
    | 5  | 8  |
```

**Expected and real results:**
```
"bool result = 5 > 8;"
A: 5, B: 8
```

### Negative case:

**.feature:**
```
Scenario Outline: Parse comparisons
  When code block "bool result = <a> < <b>;" is sent
  Then parsed variables are <a> and <b>
  Examples:
    | a  | b  |
    | 5  | 8  |
```

**Expected result:**
```
"bool result = 5 < 8;"
A: 5, B: 8
```

**Real result:**
```
[FAIL] Test :: Parse int variables :: #1: Examples table did not provide value for ` <b`. Scenario outline: `Parse comparisons`. Examples: ``. Row index: 0.
   at Xunit.Gherkin.Quick.GherkinScenarioOutlineExtensions.<>c__DisplayClass2_0.<DigestExampleValuesIntoStep>g__matchEvaluator|0(Match match)
   at System.Text.RegularExpressions.Regex.<>c.<Replace>b__84_0(ValueTuple`5& state, Match match)
   at System.Text.RegularExpressions.RegexRunner.Scan[TState](Regex regex, String text, Int32 textstart, TState& state, MatchCallback`1 callback, Boolean reuseMatchObject, TimeSpan timeout)
   at System.Text.RegularExpressions.Regex.Run[TState](String input, Int32 startat, TState& state, MatchCallback`1 callback, Boolean reuseMatchObject)
   at System.Text.RegularExpressions.Regex.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at Xunit.Gherkin.Quick.GherkinScenarioOutlineExtensions.DigestExampleValuesIntoStep(ScenarioOutline this, String exampleName, Int32 exampleRowIndex, Dictionary`2 rowValues, Step outlineStep)
   at Xunit.Gherkin.Quick.GherkinScenarioOutlineExtensions.ApplyExampleRow(ScenarioOutline this, String exampleName, Int32 exampleRowIndex)
   at Xunit.Gherkin.Quick.ScenarioOutlineExecutor.ExecuteScenarioOutlineAsync(Feature featureInstance, String scenarioOutlineName, String exampleName, Int32 exampleRowIndex, String featureFilePath)
   at Xunit.Gherkin.Quick.Feature.ScenarioOutline(String scenarioOutlineName, String exampleName, Int32 exampleIndex, String featureFilePath)
```

### Thoughts

I guess now I can see more sense in [the DataTable and DocString examples substitution problem](https://github.com/ttutisani/Xunit.Gherkin.Quick/issues/148), as the parser starts with "<>" occurrences within the provided values and then search for it inside the Examples table, not with exploring the Examples table and then looking for what could be substituted inside the text for each specific token. It is something I was not aware of.

Looks like there could be two possible ways of fixing it:
1. Do not search for Examples while parsing the steps initially and finding a "<>" pair. Instead, scan the Examples table for every step inside a Scenario Outline test and then seek for specific "<value>" occurrences. Not sure if it's a good and suitable for current logic way of doing things.
2. Pick the smallest pair of "<" and ">" inside the text instead of a wider range like in the negative case. However, this could break already existing things, so it sounds like another configurable feature... However x2, as I know, popular BDD libraries for other languages stick to this logic.

**Comment by farost** [comment]
@ttutisani Sorry for bombing you with these issues! What do you think about this one?

**Comment by ttutisani** [comment]
The first option is less preferred because it will make things loosely defined and will be a hole of errors (having a placeholder in the step and not matching it with anything without even noticing). I prefer a stricter design when the framework does not allow such things implicitly.

The second option is more like it. I think it must be as simple as distinguishing the placeholder from anything else. In your case, I can clearly see that you don't have placeholders because the placeholder must not start with a space.

So for now, without going into more complications, I would simply fix the matching regex to only match placeholders that don't start and don't end with a space. i.e., `<abc>` is a good placeholder, but `< abc>` is not.

https://github.com/ttutisani/Xunit.Gherkin.Quick/blob/83d201199033c33c1d65a6966a11125d244110e3/source/Xunit.Gherkin.Quick/CoreModel/Scenario/GherkinScenarioOutlineExtensions.cs#L15

This regex will match wrong placeholders too. So it can be fixed to only match the right placeholders.

**Comment by farost** [comment]
You're right, it would be sufficient for my case. I just decided not to offer the mentioned fix as it would still leave simple wrong errors such as `<a><<b>`, which is less human readable, but grammatically correct.

If you're satisfied with this quick fix from my side, I'll be ready to send a pull request within 24h. I'm also open to think about something a bit "smarter", but I also don't want to break anything in the process.

**Comment by farost** [comment]
And we could also think about "<=" operator. This placeholder does not start with a space, but it contains a space between the equal sign and the second variable: "<= <b>".

**Comment by ttutisani** [comment]
Good point. So the operator must start with an alphanumeric and must end with an alphanumeric (a..z, 0..9).

**Comment by farost** [comment]
So:
1. First char [A-Z | a-z | 0-9]
2. Anything between
3. Last char [A-Z | a-z | 0-9]
?

**Comment by farost** [comment]
Alright, I'm going to take care of it and write some unit tests with corner cases so we could discuss it if there is something wrong. Thanks!

**Comment by farost** [comment]
I've made a fix and added some unit tests for base cases: [PR URL](https://github.com/ttutisani/Xunit.Gherkin.Quick/pull/150). **However**, this PR is not ready for a full review: I want to add some more tests for DataTables and DocStrings. But you can check the currently existing test cases for step descriptions and the fixed RegExp if you have energy and time for it, so I could include your suggestions to the next commit as well.

**Comment by farost** [comment]
Ready!

**Comment by ttutisani** [comment]
The Nuget is uploaded. Must be soon listed in search and available for the upgrade.

**Comment by farost** [comment]
It works, thanks!
