### ISSUE TITLE
Hide individual steps from the test runner

### ISSUE THREAD

**Issue by csurfleet** [ttutisani/Xunit.Gherkin.Quick#3]
While the Specifications and Scenarios show up brilliantly in the test runner, there is also an entry for each step. These extra entries are not runnable, but do clog up the interface, and will do so especially once many scenarios are implemented. I'd like these extras to be hidden if possible.

**Comment by ttutisani** [comment]
Steps didn't show up for me ever. Can you put here a screenshot or something? In the test explorer I never saw them (as long as you derive from Feature class).

**Comment by ChristianPejrup** [comment]
I think PR #12 is a fix for this issue.

**Comment by ttutisani** [comment]
Which is merged now. I'll close this issue then. @csurfleet can you please confirm it fixes the issue?

**Comment by csurfleet** [comment]
Just checked this and yes its removed the individual steps - great work Christian!

**Comment by ttutisani** [comment]
Good thanks for confirming! closing this now. Good job.
