### ISSUE TITLE
Visual studio extension + IOC

### ISSUE THREAD

**Issue by mihaibanu** [ttutisani/Xunit.Gherkin.Quick#36]
Hello Tengiz,

I didn't see/know how to contact you so I created this issue.

I really appreciate the work that you've put into this project, so I've created a visual studio extension to help get this thing up to par(or close to) the specflow project. I'll be looking to contributing here as well.
VS extension: https://github.com/mihaibanu/Gherkin.Xunit.Quick.VS.Extension

Right now it doesn't do much, it adds two item templates for the "Calculator.feature" and the Calculator.cs, and it automatically sets the "CopyToOutputFolder" flag to true.

Looking to add towards automatic navigation, step generation and code completion.

I use specflow extensively for .net framework projects and I'm wondering if there is some sort of IoC mechanism that this framework can take advantage on. For example, at the start of each scenario it would be cool if the application under test could create the containers and behave just like the main application would. If not, how can I help?

Regards,
Mihai

**Comment by ttutisani** [comment]
Hi Mihai,

Good idea behind the extension!

I didn't understand this part. Can you please clarify?

> For example, at the start of each scenario it would be cool if the application under test could create the containers and behave just like the main application would.

In general, your observation is right, this framework does not use IoC, and I don't see much need for it. But I'm curious to hear what you exactly meant. Specifically, how will it help you with your work if it supported IoC?

**Comment by mihaibanu** [comment]
Let's take the example for the Calculator feature. Ideally it would be something like this:
```
Calculator : ICalculator
{
   //implementation
}
```

```
[FeatureFile("./Calculator.feature")]
public sealed class AddTwoNumbers : Feature
{
    _private ICalculator _calculator;
    public AddTwoNumbers(ICalculator calculator) { _calculator = calculator; }

    [When(@"I press add")]
    public void I_press_add()
    {
        _calculator.Add(first,second);
    }
}
```

And somewhere in the Project there would be a way via unity/autofac/etc to define what the ICalculator would be.
That way all the dependencies would resolve and you could test different calculators and instantiate deeply nested objects.

**Comment by mihaibanu** [comment]
Fair enough. Just to be clear, I don't want to do it in the framework. Dependency injection is not and should not be part of a test framework because that's out of scope. Specflow doesn't do it in the framework, nor should it, it does it via a plugin.

I'm just wondering how it would be best to tackle this, I really like this approach because it lets me do testing faster, cleaner, and the tests look just like an app use case. It's purely cosmetic to be honest.

Is there some sort of 'step' before execution where I can plugin this functionality?

**Comment by ttutisani** [comment]
I also don't want a plugin to be supported by this framework. Plugin means it will become something the framework needs to support. So, I won't be willing to merge a pull request with such change into the code. Just setting expectations upfront.

However, I do want to understand how exactly you see the container helping you. Maybe I can suggest some other way to achieve that.

If you just wanted a container support (and I don't see that related to the VS extension at all), you could do that by creating a "wrapper" framework around this one. e.g. you could have a class which derives from `Feature` and define container there. Then, whoever needs the container support, would derive from that new base class instead of deriving from `Feature` directly. But again, that's just how I would tackle the container support. But this may not be the best way to achieve what you are trying to achieve in the VS extension.

**Comment by mihaibanu** [comment]
The VS extension is something completely different. I want it to have item templates, project templates, syntax highlighting, code completion and code navigation. Right now it only has item templates. I'm doing syntax highlighting next since it looks pretty easy to add for gherkin.

Thanks for the pointer towards the Feature class. I'm just looking for a way to init the container and achieve that functionality for my code base and I was hoping that there is an easy way to do that. I guess I'll start reading through the code and see how it executes and do a package that will achieve the same functionality.

**Comment by mihaibanu** [comment]
You may close it. I will message you again when the extension has more features and maybe you can add it to the list of useful extensions.

**Comment by ttutisani** [comment]
Agreed.
