### ISSUE TITLE
Accessing same step definition using multiple steps

### ISSUE THREAD

**Issue by SDETRK** [ttutisani/Xunit.Gherkin.Quick#50]
Hi,
In specflow we can access the same step definition using multiple steps. For example: A "Given" step in a test scenario can be used as a "When" step in another scenario. So instead of duplicating the code we can use:

[Given(@"I search for '(.*)'")]
[When(@"I search for '(.*)'")]
public void ISearchFor(string searchTerm)
{
  ...
}

It would be very useful as well in the case of  "And" step in Xunit.Gherkin.Quick for example:

[And(@"I search for '(.*)'")]
[When(@"I search for '(.*)'")]
public void ISearchFor(string searchTerm)
{
  ...
}

**Comment by ttutisani** [comment]
Agreed, that makes sense as an expectation.
Will look into it.

**Comment by SDETRK** [comment]
great, thank you!

**Comment by SDETRK** [comment]
sorry I closed it by mistake. I reopened the issue

**Comment by ttutisani** [comment]
No worries!

**Comment by christianh25** [comment]
We have the same issue in our project. This would be a nice added feature!! Any chance we have an ETA?

**Comment by ttutisani** [comment]
2 weeks max ETA and should be out.
I will provide updates here along the way.

**Comment by ttutisani** [comment]
This work is in progress now. So far everything seems to be on track.

Branch diff: https://github.com/ttutisani/Xunit.Gherkin.Quick/compare/sharedStepMethod?expand=1

**Comment by ttutisani** [comment]
Version 3.2.0 is uploaded to Nuget.
It will become available for download after validation and indexing (internal steps to Nuget) are complete. Expert to see new downloadable version in couple of hours.

Let me know if any issues noticed.

**Comment by ttutisani** [comment]
Oh, forgot to mention the most important part: Version 3.2.0 is for supporting shared step method to match multiple scenario steps in Gherkin feature file.

**Comment by ttutisani** [comment]
Link to the instructions: https://github.com/ttutisani/Xunit.Gherkin.Quick/blob/master/docs/shared-step-method.md (basically it works as it was asked here in this issue anyway)

**Comment by ttutisani** [comment]
Closing the issue since this functionality is already out.
If any problems found with it, please open a new issue.

**Comment by SDETRK** [comment]
Thank you very much for the fix, we will try it!
