### ISSUE TITLE
Tests don't work

### ISSUE THREAD

**Issue by david-mcmanus** [ttutisani/Xunit.Gherkin.Quick#73]
Test Explorer cannot find the test also when trying to create a new feature I get a file not found.
Using empty solution with only a single feature/scenario.
Target Framework: .NET Core 2.2
MS Visual Studio Enterprise 2017 Version: 15.9.7
Not sure if it is an issue with Gherkin Quick or local install issue.
Including test solution.
[TestXunitGherkinQuick.zip](https://github.com/ttutisani/Xunit.Gherkin.Quick/files/2954057/TestXunitGherkinQuick.zip)

**Comment by ttutisani** [comment]
You didn't follow the getting started tutorial step by step. Quote from there:

>**Important**: change feature file properties to ensure it gets copied into output directory. Set the value of Copy to Output Directory to Copy Always or Copy if Newer.

Getting started tutorial can be found on the home page of this project.

**Comment by ttutisani** [comment]
@david-mcmanus did my previous hint answer your question, or do you still have issues?

**Comment by ttutisani** [comment]
I haven't received a response for a while, but I consider this ticket as resolved anyway, because after changing the setting as mentioned above the tests appeared and ran fine.
Please feel free to reopen the ticket if the issue persists, or start a new one if there are other issues.
Thank you!
