### ISSUE TITLE
Test not discovered in NetCore xunit test project MacOS

### ISSUE THREAD

**Issue by AlexTeixeira** [ttutisani/Xunit.Gherkin.Quick#74]
Hi,

I'm trying to work with a simple project in macOS, and when I run `dotnet test`, any test are discovered.

1. dotnet info 

```
SDK .NET Core (reflétant tous les global.json) :
 Version:   2.2.100
 Commit:    51868761f2

Environnement d'exécution :
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.100/

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed
```

2. The csproj of my project 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="Xunit.Gherkin.Quick" Version="3.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
  </ItemGroup>

   <ItemGroup>
    <None Update="features\bookvtc.feature">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

```

1. The feature file and a simple cs file

> Feature: VTC Testing
> 
>   Given book a vtc

```
using Xunit.Abstractions;
using Xunit.Gherkin.Quick;
using Feature = Xunit.Gherkin.Quick.Feature;

namespace domainacceptance.steps
{
    [FeatureFile(@".\features\bookvtc.feature")]
    public sealed class bookvtc : Feature
    {
        [Given(@"book a vtc")]
        public void Test()
        {
        }
    }
}
```

I already check the feature file location in my bin folder, and it's as it place.

I also followed this quick tutorial, to check if my project is good : 
http://bristoltech.net/using-cucumber-with-net-core/

And after some check, I decide to download the project located in github and to run `dotnet test`, but I have the same issue, any test was discovered.

Have you an idea ?

**Comment by ttutisani** [comment]
@AlexTeixeira your feature file syntax is incorrect. You need to follow the Gherkin language syntax, otherwise, it won't discover any scenarios.

Specifically, your feature file is missing `Scenario`.

I recommend that you follow the quick start tutorial and it should work. https://github.com/ttutisani/Xunit.Gherkin.Quick

**Comment by AlexTeixeira** [comment]
@ttutisani Thanks for your quick answers.

Following the feature file and the cs file in your github. Now I'm able to run tests in my console :).

I think now I should read Gherkins documentation to learn more about the syntax.

Many thanks.
